### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Narigo** [geon/estimator#1]
Hi there,

I've tried out the demo and it looks really nice. The idea behind this is really great and quickly gives me an overview how much time we have to plan for a specific project.

There was some weird behavior when trying to open a project in a private browser window (created some "empty" tasks). Would like to understand why that happened and maybe help fixing it. Without a license, I don't want to touch anything here - and if I won't be able to use it inside of my own infrastructure I won't even be able to use it for real things.

Could you add a License file that tells us what we may do with the code here? :)

Thanks a lot!

**Comment by geon** [comment]
Thanks for offering to help!

Estimator is now under the MIT license.
