### ISSUE TITLE
Listen to keydown instead of keyup

### ISSUE THREAD

**Issue by rinopo** [geon/estimator#2]
Hi,

I've tried the product and it looks very promising.
I'm eager to use it in real projects but I have a little problem.

When a user is using some Input Method (e.g. when typing in Japanese), listening to the keyup event for the keycode 13 doesn't always seem desirable, since the Return key is used by the Input Method (input source front-end) to accept a conversion of the typed phonetic characters to the proper display characters. So pressing the Return key should only insert the composed phrase into the text field and allow further composition, instead of submitting form etc.

To avoid this hasty behavior, I think you should listen to the keydown event instead of keyup for the keycode 13, since the former returns the keycode 229 to indicate that the IM is busy and returns the keycode 13 only when a Return character is really intended, whereas the keyup event always returns the key code 13 regardless of the IM's status.

Thanks in advance for your consideration!

---

Keycode when a Return character is entered w/ normal input or IM:

|  | keydown | keypress | keyup |
| --- | --- | --- | --- |
| Firefox 35 | 13 | 13 | 13 |
| IE 11 | 13 | 13 | 13 |
| Chrome 40 | 13 | 13 | 13 |
| safari 8 | 13 | 13 | 13 |

Keycode when IM is busy:

|  | keydown | keypress | keyup |
| --- | --- | --- | --- |
| Firefox 35 | n/a | n/a | 13 |
| IE 11 | 229 | n/a | 13* |
| Chrome 40 | 229 | n/a | 13 |
| safari 8 | 229 | n/a | 13 |

*=Fires twice.

Result with older browsers can be found [here](http://d.hatena.ne.jp/end0tknr/20130808/1375953351) (basically the same).

**Comment by geon** [comment]
Thanks!

Fixed now. Please test it.

**Comment by rinopo** [comment]
Seems to be working nicely!
Thanks a lot!

**Comment by geon** [comment]
Σ:3
