### ISSUE TITLE
Missing README

### ISSUE THREAD

**Issue by phanimahesh** [geon/estimator#3]
This project is missing a README. A screenshot of the github pages site and a short description would be great.

Nice project BTW.

Also, adding a github link to the site would be good. I had to manually edit the URL to reach here.

**Comment by PawelMorawian** [comment]
There is a manual.md in public/

**Comment by phanimahesh** [comment]
But README (in any format) is offered a very special status in all GitHub repositories. The manual was linked on the site and I could locate it fairly easily. Perhaps the same can be symlinked as README?

On a sidenote, does github honor symlinked READMEs?

**Comment by geon** [comment]
Added!

**Comment by phanimahesh** [comment]
Thanks! Looks great! :)
