### ISSUE TITLE
Install & Run?

### ISSUE THREAD

**Issue by ghost** [geon/estimator#5]
Looks very interesting, but for the folks that are not node+grunt+express gurus would it be possible to have a very brief Getting Started?

**Comment by geon** [comment]
Done. Check the readme.

Not that if you just want to _use_ Estimator, it is available on the gh-pages website: http://geon.github.io/estimator .

**Comment by stefanoco** [comment]
Thanks a lot! Actually I'm trying to figure out if I'm able to modify according to our needs and propose any useful result that might come out of this. Very good job!

**Comment by geon** [comment]
If you are only interested in the frontend, you can skip installing the backend, and change the backend URL in client/Gruntfile.js to point to the official backend server. The URL is in a comment.

**Comment by stefanoco** [comment]
thanks!!
